source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AlamofireRSS_Example' do
  pod 'AlamofireRSS', :path => '../'
end

target 'AlamofireRSS_Tests' do
  pod 'AlamofireRSS', :path => '../'
end
