source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AlamofireRSS_Example', :exclusive => true do
  pod 'AlamofireRSS', :path => '../'
end

target 'AlamofireRSS_Tests', :exclusive => true do
  pod 'AlamofireRSS', :path => '../'

  
end
